### PR TITLE
A few modif

### PR DESCRIPTION
**Pull request by nouiz**

### CODE REVIEW

**Comment by nouiz** [comment]
The last commit isn't sure. It fix a bug in the DLT logistic_sgd when I use it in this branch:

https://github.com/nouiz/DeepLearningTutorials/tree/fct_copy

What do you think of all my modif here and in the last commit? Why that copy is needed?

**Comment by nouiz** [comment]
My last commit make this test fail:

  File "/u/bastienf/repos/Theano/theano/compile/tests/test_function_module.py", line 277, in test_copy_share_memory

We need to add a test for the case my last commit fix. Can you do it?

Sorry for the long time for review.

**Comment by ChienliMa** [comment]
On my laptop only a KnownFailure raised, which make the test failed. In test_none().
Other tests were ok.  Yet  there's an `Exception AttributeError:` which I cannot tract. Do you mean this one?

**Comment by nouiz** [comment]
knownfailure are ok. Depending how you run Theano tests, they can be shown
or skiped. Just ignore them.

For the attributeerror, this is not related to your PR and was fixed in
master. If you rebase, it won't appear again.

What do you think of my last commit?

**Comment by nouiz** [comment]
I forgot to add the last commit in my PR. The commit that fix the DLT
logistic_sgd.py example is in this branch now:

https://github.com/nouiz/Theano/tree/ChienliMa-swapSV

It is with this commit that one test fail under
compile/tests/test_function*.py

**Comment by ChienliMa** [comment]
I saw your commit.

This copy generates different storage between original and copied `In`s.

If the `In` instance is mutable, which mean its variable is sharedvariable and has update, they should not be the same. And different times of call to different function will generate different result.

If it's immutable, we will share the storage again to save memory. This process is carried in a loop from line `652` to line `662`.

``` python
 for in_ori, in_cpy, ori, cpy in zip(maker.inputs, f_cpy.maker.inputs,
                                            self.input_storage,
                                            f_cpy.input_storage):

            # Share immutable ShareVariable and constant input's storage
            swapped = swap is not None and in_ori.variable in swap_svs_ori

            is_const = isinstance(in_ori.variable, theano.tensor.Constant)
            if (is_const or not in_ori.mutable) and not swapped:
                cpy.data = ori.data
                in_cpy.value = in_ori.value
```

Should I add a comment for this?

**Pull request merged**
